# Generated by Django 4.0.2 on 2022-03-31 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultant', '0011_rename_category_description_consultancytype_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='expertise',
            field=models.CharField(default='', max_length=150),
        ),
    ]
