# Generated by Django 4.0.2 on 2022-04-04 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultant', '0013_remove_consultant_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='timming',
            field=models.CharField(default='', max_length=255),
        ),
    ]
