# Generated by Django 4.0.2 on 2022-04-04 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultant', '0014_consultant_timming'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultant',
            name='timming',
            field=models.CharField(max_length=255),
        ),
    ]
