# Generated by Django 4.0.2 on 2022-04-04 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultant', '0015_alter_consultant_timming'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultant',
            name='timming',
        ),
        migrations.AddField(
            model_name='consultant',
            name='end_time',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='consultant',
            name='start_time',
            field=models.CharField(default='', max_length=255),
        ),
    ]
