# Generated by Django 4.0.2 on 2022-04-05 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0009_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='remark',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
